test bash fix

diff --git a/.github/workflows/rebuild_prebuilts.yml b/.github/workflows/rebuild_prebuilts.yml
--- a/.github/workflows/rebuild_prebuilts.yml
+++ b/.github/workflows/rebuild_prebuilts.yml
@@ -34,7 +34,16 @@ jobs:
         id: build-docker
         run: |
           bash ./build-docker.sh
-          bash ./checkdeployment.sh
+          # check for output files
+          DEPLOYFILECOUNT=$(ls -1 . | wc -l)
+          if [ "$DEPLOYFILECOUNT" -ge 2 ]
+          then
+          echo "Done! Your image(s) should be in deploy/"
+          exit 0
+          else
+          echo "The script failed" >&2
+          exit 1
+          fi
         working-directory: dockerbuildsystem
       - 
         name: Create Release
